language: node_js
node_js:
  - "node"

script: npm run coveralls && npm run nexebuild

deploy:
  provider: releases
  api_key: "$OAUTH_KEY"
  file: 
    - ./build/savulcoin-linux-x64
    - ./build/savulcoin-linux-x86
    - ./build/savulcoin-windows-x64.exe
    - ./build/savulcoin-windows-x86.exe
    - ./build/savulcoin-mac-x64
  
  skip_cleanup: true